apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-car-owner-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-car-owner-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: kub-car-owner-ui
        tier: frontend
    spec:
      containers:
        - name: kub-car-owner-angular
          image: localhost:5000/kub-car-owner-ui:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5
          ports:
            - containerPort: 80
