version: "3.9"

services:
  postgres_carowner_db:
    image: postgres:14.1
    container_name: postgres_carowner_db
    hostname: postgres_carowner_db
    deploy:
      mode: global
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=carowner
    volumes:
      - "carowner_db:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      carownernet:
        aliases:
          - postgres_carowner_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "carowner", "-U", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  carownernet:
volumes:
  carowner_db:
    name: carowner_db