version: "3.9"

services:
  carowner-service:
    container_name: carowner-service
    build:
      context: ../car-owner-service
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - DB_URL=jdbc:postgresql://postgres_carowner_db:5432/carowner
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
    networks:
      carownernet:
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://carowner-service:8080/owner/list"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      postgres_carowner_db:
        condition: service_healthy

  carowner-ui:
    container_name: carowner-ui
    build:
      context: ../car-owner-ui
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      carownernet:
    depends_on:
      carowner-service:
        condition: service_healthy

  postgres_carowner_db:
    image: postgres:14.5
    container_name: postgres_carowner_db
    hostname: postgres_carowner_db
    deploy:
      mode: global
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=carowner
    volumes:
      - "carowner_db:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      carownernet:
        aliases:
          - postgres_carowner_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "carowner", "-U", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  carownernet:
volumes:
  carowner_db:
    name: carowner_db