apiVersion: v1
kind: Service
metadata:
  name: database-node-service
spec:
  type: NodePort
  selector:
    component: database-service
  ports:
    - port: 5432
      target: 5432
      nodePort: 31502